version: '3.8'

services:
  chrome:
    image: browserless/chrome:latest
    environment:
      - MAX_CONCURRENT_SESSIONS=10
      - CONNECTION_TIMEOUT=300000
      - MAX_QUEUE_LENGTH=20
    ports:
      - "3000:3000"
    restart: no

  app:
    build: .
    environment:
      - CHROME_URL=ws://chrome:3000
    ports:
      - "2337:8080"
    depends_on:
      - chrome
    restart: no